### ISSUE TITLE
New Trace log level in logrus

### ISSUE THREAD

**Issue by dgsb** [nullseed/logruseq#3]
Hello, I'm just opening this issue to let you know, the next release of logrus (v1.2.0) will add a new trace level named Trace below Debug.
Here is the PR for reference sirupsen/logrus#844
You may want to take into account this new level.

**Comment by nblumhardt** [comment]
Just checking out the code, it looks like no level mapping is done when sending events, but the `Levels()` function is explicit about handling a subset of properties. Since Seq will happily accept both `Verbose` and `Panic`, it seems like the best response to this is to make logruseq transparent from a level perspective and just send through to Seq whatever logrus gives it.
